### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/twitter/metadata.pkl'

### ISSUE THREAD

**Issue by hoyeunglee** [suriyadeepan/tf_seq2seq_wrapper#68]
martin@ubuntu:~/Downloads/practical_seq2seq$ python3 03-Twitter-chatbot.py 
Traceback (most recent call last):
  File "03-Twitter-chatbot.py", line 12, in <module>
    metadata, idx_q, idx_a = data.load_data(PATH='datasets/twitter/')
  File "/home/martin/Downloads/practical_seq2seq/datasets/twitter/data.py", line 205, in load_data
    with open(PATH + 'metadata.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/twitter/metadata.pkl'

**Comment by virajrai** [comment]
you need to unzip the seq2seq.twitter.tar.gz. Execute the following:

`tar seq2seq.twitter.tar.gz`
