### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by irdanish11** [suriyadeepan/tf_seq2seq_wrapper#75]
<log> Building Graph Traceback (most recent call last):

  File "<ipython-input-13-1e0d5aa9a521>", line 1, in <module>
    runfile('D:/Study/BE_Electronics/Semester8/FYP_Phase2/TwitterChatlogPreprocessing/Twitter-chatbot.py', wdir='D:/Study/BE_Electronics/Semester8/FYP_Phase2/TwitterChatlogPreprocessing')

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Study/BE_Electronics/Semester8/FYP_Phase2/TwitterChatlogPreprocessing/Twitter-chatbot.py", line 39, in <module>
    num_layers=3

  File "D:\Study\BE_Electronics\Semester8\FYP_Phase2\TwitterChatlogPreprocessing\seq2seq_wrapper.py", line 77, in __init__
    __graph__()

  File "D:\Study\BE_Electronics\Semester8\FYP_Phase2\TwitterChatlogPreprocessing\seq2seq_wrapper.py", line 62, in __graph__
    feed_previous=True)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 358, in embedding_rnn_seq2seq
    encoder_cell = copy.deepcopy(cell)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 161, in deepcopy
    y = copier(memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 395, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)

**Comment by lcarnevale** [comment]
Hello,

I resolved that problem downgrading tensorflow to 1.0.0.
Give a look here: https://github.com/tensorflow/tensorflow/issues/11157

**Comment by minda163** [comment]
> Hello,
> 
> I resolved that problem downgrading tensorflow to 1.0.0.
> Give a look here: [tensorflow/tensorflow#11157](https://github.com/tensorflow/tensorflow/issues/11157)

It's no use for me.
