### ISSUE TITLE
InvalidArgumentError: Failed to create a directory:ckpt

### ISSUE THREAD

**Issue by irdanish11** [suriyadeepan/tf_seq2seq_wrapper#76]
Traceback (most recent call last):

  File "<ipython-input-1-1e0d5aa9a521>", line 1, in <module>
    runfile('D:/Study/BE_Electronics/Semester8/FYP_Phase2/TwitterChatlogPreprocessing/Twitter-chatbot.py', wdir='D:/Study/BE_Electronics/Semester8/FYP_Phase2/TwitterChatlogPreprocessing')

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Study/BE_Electronics/Semester8/FYP_Phase2/TwitterChatlogPreprocessing/Twitter-chatbot.py", line 51, in <module>
    sess = model.train(train_batch_gen, val_batch_gen)

  File "D:\Study\BE_Electronics\Semester8\FYP_Phase2\TwitterChatlogPreprocessing\seq2seq_wrapper.py", line 153, in train
    saver.save(sess, self.ckpt_path + self.model_name + '.ckpt', global_step=i)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1441, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)

  File "C:\Users\IrfanDanish\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Failed to create a directory: ckpt	witter; Invalid argument

**Comment by irdanish11** [comment]
Can anyone please help me with this issue
