### ISSUE TITLE
sess.run() method issue

### ISSUE THREAD

**Issue by ghost** [suriyadeepan/tf_seq2seq_wrapper#79]
Python = 3.5
Tensorflow = 0.12.1 
OS: - Windows

The dataset is changed for college enquiry chatbot.

Running 'the_best_chatbot.py' and then asking a question to the chatbot error occurs as shown below and the chatbot is unable to run:-

################Start Chatting Below########################

You: Does the college provide necessary information?
Traceback (most recent call last):

  File "<ipython-input-39-4d3d9f83fa64>", line 72, in <module>
    answer = respond(question)

  File "<ipython-input-39-4d3d9f83fa64>", line 65, in respond
    answer = model.predict(session, encoded_question)[0]

  File "R:\Project - Chat Bot\The Best ChatBot - Copy\seq2seq_wrapper.py", line 179, in predict
    dec_op_v = sess.run(self.decode_outputs_test, feed_dict)

  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)

  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)

  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)

  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)

FailedPreconditionError: Attempting to use uninitialized value decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias
	 [[Node: decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias/read = Identity[T=DT_FLOAT, _class=["loc:@decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias"], _device="/job:localhost/replica:0/task:0/cpu:0"](decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias)]]

Caused by op 'decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias/read', defined at:
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 269, in <module>
    main()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 265, in main
    kernel.start()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-39-4d3d9f83fa64>", line 43, in <module>
    num_layers = 3)
  File "R:\Project - Chat Bot\The Best ChatBot - Copy\seq2seq_wrapper.py", line 83, in __init__
    __graph__()
  File "R:\Project - Chat Bot\The Best ChatBot - Copy\seq2seq_wrapper.py", line 62, in __graph__
    xvocab_size, yvocab_size, emb_dim)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\seq2seq.py", line 357, in embedding_rnn_seq2seq
    feed_previous=feed_previous)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\seq2seq.py", line 280, in embedding_rnn_decoder
    loop_function=loop_function)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\seq2seq.py", line 146, in rnn_decoder
    output, state = cell(inp, state)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\rnn_cell.py", line 589, in __call__
    projected = _linear(output, self._output_size, True)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\rnn_cell.py", line 916, in _linear
    bias_start, dtype=dtype))
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\variables.py", line 370, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\rahul\Anaconda3\envs\the_best_chatbot\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias
	 [[Node: decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias/read = Identity[T=DT_FLOAT, _class=["loc:@decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias"], _device="/job:localhost/replica:0/task:0/cpu:0"](decoder/embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/OutputProjectionWrapper/Linear/Bias)]]

Please help. Thanking you in Advance.

**Comment by saran-gangster** [comment]
i hope retraining the model will help you
and try  using new [](https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html)

**Comment by saran-gangster** [comment]
i hope retraining the model will help you and also use a new [dataset](https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html)
